function(gateway_enable_warnings target)
  if(MSVC)
    target_compile_options(${target} INTERFACE /W4)
    if(GATEWAY_ENABLE_WARNINGS_AS_ERRORS)
      target_compile_options(${target} INTERFACE /WX)
    endif()
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(${target} INTERFACE -Wall -Wextra -Wpedantic)
    if(GATEWAY_ENABLE_WARNINGS_AS_ERRORS)
      target_compile_options(${target} INTERFACE -Werror)
    endif()
  else()
    message(WARNING "No project warning profile is defined for ${CMAKE_CXX_COMPILER_ID}")
  endif()
endfunction()
